// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {session} from '../models';

export function AddQuickJump(arg1:string,arg2:number,arg3:string):Promise<void>;

export function AddSubtask(arg1:string,arg2:string,arg3:string):Promise<main.SubtaskInfo>;

export function AssignToGroup(arg1:string,arg2:string):Promise<void>;

export function AttachBackgroundAgent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function AttachBackgroundAgentAsTab(arg1:string,arg2:string,arg3:string):Promise<number>;

export function AttachSession(arg1:string,arg2:number):Promise<string>;

export function BrowseDirectory(arg1:string):Promise<string>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function ClearLog(arg1:string):Promise<void>;

export function CloseTab(arg1:string,arg2:number):Promise<void>;

export function CreateBackup():Promise<void>;

export function CreateGroup(arg1:string):Promise<main.GroupInfo>;

export function CreateProject(arg1:string):Promise<main.ProjectInfo>;

export function CreateSession(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string):Promise<main.SessionInfo>;

export function CreateSessionFromTemplate(arg1:string,arg2:string,arg3:string):Promise<main.SessionInfo>;

export function CreateTab(arg1:string,arg2:boolean,arg3:string,arg4:string,arg5:string,arg6:string):Promise<number>;

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<main.TaskInfo>;

export function CycleYoloMode(arg1:string,arg2:number):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function DeleteCommandGroup(arg1:string):Promise<void>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSessionTemplate(arg1:string):Promise<void>;

export function DeleteSubtask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteTab(arg1:string,arg2:number):Promise<void>;

export function DeleteTask(arg1:string,arg2:string):Promise<void>;

export function DetachSession(arg1:string):Promise<void>;

export function DetectionPatternsVersion():Promise<number>;

export function DiscoverLocalSchemes():Promise<Array<main.ImportedScheme>>;

export function EmptyTrash():Promise<void>;

export function ExportSessions(arg1:Array<string>):Promise<string>;

export function FetchOnlineSchemes(arg1:Array<string>):Promise<Array<main.ImportedScheme>>;

export function ForkSession(arg1:string,arg2:number):Promise<main.ForkResult>;

export function ForkToNewSession(arg1:string,arg2:string,arg3:string):Promise<main.SessionInfo>;

export function ForkToNewTab(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetActiveProjectID():Promise<string>;

export function GetActivities():Promise<Record<string, string>>;

export function GetAgents():Promise<Array<main.AgentInfo>>;

export function GetAllTasks():Promise<Array<main.TaskOverviewItem>>;

export function GetAppLog():Promise<main.AppLog>;

export function GetBackgroundAgentLogs(arg1:string):Promise<string>;

export function GetBackups():Promise<Array<main.BackupInfo>>;

export function GetClaudeUsage():Promise<main.ClaudeUsageInfo>;

export function GetCodexUsage():Promise<main.CodexUsageInfo>;

export function GetCommands():Promise<main.CommandLibraryInfo>;

export function GetExtraArgs(arg1:string,arg2:number):Promise<string>;

export function GetFullDiff(arg1:string,arg2:number):Promise<main.DiffData>;

export function GetFullDiffFileList(arg1:string,arg2:number):Promise<Array<session.DiffFileSummary>>;

export function GetFullDiffFiles(arg1:string,arg2:number):Promise<Array<session.DiffFile>>;

export function GetFullDiffForFile(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<session.DiffFile>;

export function GetGitBranch(arg1:string):Promise<main.GitBranchInfo>;

export function GetGitCommitDiff(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<session.DiffFile>;

export function GetGitCommitFiles(arg1:string,arg2:string):Promise<Array<session.DiffFileSummary>>;

export function GetGitHistory(arg1:string,arg2:string,arg3:number):Promise<main.GitHistoryPage>;

export function GetGroups():Promise<Array<main.GroupInfo>>;

export function GetHistoryPreview(arg1:main.HistoryEntryInfo):Promise<string>;

export function GetLastLine(arg1:string):Promise<string>;

export function GetLockStatus():Promise<main.LockStatusInfo>;

export function GetLog(arg1:string):Promise<main.AppLog>;

export function GetMultiplexerStatus():Promise<main.MultiplexerStatus>;

export function GetNextTask(arg1:string):Promise<main.TaskInfo>;

export function GetPreview(arg1:string,arg2:number):Promise<main.PreviewData>;

export function GetProjectActivityStatistics(arg1:string,arg2:number):Promise<main.ProjectActivityStatistics>;

export function GetProjectGitSummaries(arg1:string):Promise<Array<main.ProjectGitSummary>>;

export function GetProjectSessions(arg1:string):Promise<Array<main.SessionInfo>>;

export function GetProjects():Promise<Array<main.ProjectInfo>>;

export function GetQuickJump():Promise<Array<session.QuickJumpEntry>>;

export function GetResumeSessions(arg1:string,arg2:string):Promise<Array<main.AgentSessionInfo>>;

export function GetSessionDiff(arg1:string,arg2:number):Promise<main.DiffData>;

export function GetSessionDiffFileList(arg1:string,arg2:number):Promise<Array<session.DiffFileSummary>>;

export function GetSessionDiffFiles(arg1:string,arg2:number):Promise<Array<session.DiffFile>>;

export function GetSessionDiffForFile(arg1:string,arg2:string,arg3:boolean,arg4:number):Promise<session.DiffFile>;

export function GetSessionTemplates():Promise<Array<main.SessionTemplateInfo>>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetSettings():Promise<main.SettingsInfo>;

export function GetSidebarUpdates():Promise<main.SidebarUpdate>;

export function GetStatusLines():Promise<Record<string, string>>;

export function GetTabNotes(arg1:string,arg2:number):Promise<string>;

export function GetTabOrder(arg1:string):Promise<Array<number>>;

export function GetTabWorkingDirectory(arg1:string,arg2:number):Promise<string>;

export function GetTaskBackups():Promise<Array<main.BackupInfo>>;

export function GetTasks(arg1:string):Promise<Array<main.TaskInfo>>;

export function GetTasksByStatus(arg1:string,arg2:string):Promise<Array<main.TaskInfo>>;

export function GetTerminalWSPort():Promise<number>;

export function GetTerminalWSToken():Promise<string>;

export function GetTrashItems():Promise<Array<main.TrashItemInfo>>;

export function GetVersion():Promise<string>;

export function GetWindowAutoYes(arg1:string,arg2:number):Promise<boolean>;

export function GetWindowList(arg1:string):Promise<Array<session.WindowInfo>>;

export function GlobalSearch(arg1:string):Promise<Array<main.HistoryEntryInfo>>;

export function ImportSchemeFiles():Promise<Array<main.ImportedScheme>>;

export function ImportSessionFile(arg1:string,arg2:Array<string>):Promise<number>;

export function ImportSessions(arg1:string,arg2:Array<string>):Promise<number>;

export function InitHistorySearch():Promise<void>;

export function InstallMultiplexer():Promise<string>;

export function InvalidateSessionFileIndex(arg1:string):Promise<void>;

export function IsDevMode():Promise<boolean>;

export function ListBackgroundAgents():Promise<Array<main.BackgroundAgentInfo>>;

export function ListGitBranches(arg1:string):Promise<main.GitBranchList>;

export function ListOnlineSchemes():Promise<Array<main.OnlineSchemeInfo>>;

export function ListSessionDirectory(arg1:string,arg2:string,arg3:number):Promise<session.BrowseListing>;

export function LogFrontend(arg1:string):Promise<void>;

export function MoveGroup(arg1:string,arg2:number):Promise<void>;

export function MoveQuickJump(arg1:number,arg2:number):Promise<void>;

export function MoveSessionToIndex(arg1:string,arg2:number):Promise<void>;

export function MoveTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenAppLogFolder():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenLogFolder(arg1:string):Promise<void>;

export function OpenSessionFileForEdit(arg1:string,arg2:string,arg3:number):Promise<session.EditableFile>;

export function PendingUpdate():Promise<string>;

export function PerformUpdate(arg1:string):Promise<void>;

export function PermanentlyDeleteTrashItem(arg1:string):Promise<void>;

export function QuickReplyTab(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ReadSessionDirectoryFile(arg1:string,arg2:string,arg3:number):Promise<session.BrowseFile>;

export function ReadSessionFile():Promise<main.PortableFileInfo>;

export function RedrawWindow(arg1:string,arg2:number):Promise<void>;

export function RefreshDetectionPatterns():Promise<main.PatternRefreshResult>;

export function RefreshWindow(arg1:string,arg2:number):Promise<void>;

export function RemoveQuickJump(arg1:string,arg2:number):Promise<void>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RenameTab(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ReorderSession(arg1:string,arg2:number):Promise<void>;

export function ReorderTab(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartTab(arg1:string,arg2:number):Promise<void>;

export function RestartTabWithResume(arg1:string,arg2:number,arg3:string):Promise<void>;

export function RestoreBackup(arg1:string):Promise<void>;

export function RestoreDeletedSubtask(arg1:string,arg2:string,arg3:string,arg4:main.DeletedSubtaskSnapshot):Promise<void>;

export function RestoreDeletedTask(arg1:string,arg2:string,arg3:main.DeletedTaskSnapshot):Promise<void>;

export function RestoreTaskBackup(arg1:string):Promise<void>;

export function RestoreTrashItem(arg1:string):Promise<session.RestoreResult>;

export function RevertDiffFile(arg1:string,arg2:string,arg3:boolean,arg4:number,arg5:string):Promise<void>;

export function RevertDiffHunk(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function RunCommand(arg1:string,arg2:string,arg3:number,arg4:Record<string, string>):Promise<void>;

export function SaveCommand(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<string>;

export function SaveCommandGroup(arg1:string,arg2:string):Promise<string>;

export function SaveSessionAsTemplate(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SaveSessionFileEdit(arg1:string,arg2:string,arg3:string,arg4:session.FileShape,arg5:string,arg6:boolean,arg7:number):Promise<main.SaveFileEditResult>;

export function SaveSessionTemplate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean,arg8:string,arg9:Array<main.TemplateTabInfo>):Promise<string>;

export function SaveSettings(arg1:main.SettingsInfo):Promise<void>;

export function SearchSessionFileContents(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:number):Promise<session.ContentSearchResult>;

export function SearchSessionFileIndex(arg1:string,arg2:boolean,arg3:number):Promise<session.FileIndex>;

export function SelectProject(arg1:string):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function SendPrompt(arg1:string,arg2:string):Promise<void>;

export function SendPromptToWindow(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SendTaskToAgent(arg1:string,arg2:string):Promise<void>;

export function SetExtraArgs(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetGroupColor(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetLastWindowIndex(arg1:string,arg2:number):Promise<void>;

export function SetQuickJump(arg1:Array<session.QuickJumpEntry>):Promise<void>;

export function SetQuickJumpLabel(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetSessionColor(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetSessionNotes(arg1:string,arg2:string):Promise<void>;

export function SetTabColor(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SetTabFontSize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetTabNotes(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetTabStatusBar(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetTabStatusLineVisibility(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function SetTabTerminalTheme(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetTabViewBar(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetWindowAutoYes(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function StartSession(arg1:string):Promise<void>;

export function StartSessionWithResume(arg1:string,arg2:string):Promise<void>;

export function StopBackgroundAgent(arg1:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function StopTab(arg1:string,arg2:number):Promise<void>;

export function StopTaskMaster(arg1:string):Promise<void>;

export function TaskMasterAddDependency(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterAddManualTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.MCPTaskInfo>;

export function TaskMasterAddSubtask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TaskMasterAddTask(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<main.MCPTaskInfo>;

export function TaskMasterAnalyzeComplexity(arg1:string,arg2:boolean):Promise<string>;

export function TaskMasterClearSubtasks(arg1:string,arg2:string):Promise<void>;

export function TaskMasterExpandAll(arg1:string,arg2:boolean):Promise<void>;

export function TaskMasterExpandTask(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function TaskMasterGetTask(arg1:string,arg2:string):Promise<main.MCPTaskInfo>;

export function TaskMasterGetTasks(arg1:string,arg2:string):Promise<Array<main.MCPTaskInfo>>;

export function TaskMasterInit(arg1:string):Promise<void>;

export function TaskMasterNextTask(arg1:string):Promise<main.MCPTaskInfo>;

export function TaskMasterParsePRD(arg1:string,arg2:string,arg3:number):Promise<void>;

export function TaskMasterRemoveDependency(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterRemoveSubtask(arg1:string,arg2:string):Promise<void>;

export function TaskMasterRemoveTask(arg1:string,arg2:string):Promise<void>;

export function TaskMasterSendToAgent(arg1:string,arg2:string):Promise<void>;

export function TaskMasterSetStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterSetSubtaskStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterStatus(arg1:string):Promise<Record<string, any>>;

export function TaskMasterUpdateSubtask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterUpdateTask(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function TaskMasterUpdateTaskDirect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function ToggleAutoYes(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function ToggleGroupCollapse(arg1:string):Promise<void>;

export function ToggleSubtask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnfinishedTasksForSession(arg1:string):Promise<Array<main.TaskInfo>>;

export function UpdateTask(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;
