// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddQuickJump(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddQuickJump'](arg1, arg2, arg3);
}

export function AddSubtask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSubtask'](arg1, arg2, arg3);
}

export function AssignToGroup(arg1, arg2) {
  return window['go']['main']['App']['AssignToGroup'](arg1, arg2);
}

export function AttachBackgroundAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AttachBackgroundAgent'](arg1, arg2, arg3, arg4);
}

export function AttachBackgroundAgentAsTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttachBackgroundAgentAsTab'](arg1, arg2, arg3);
}

export function AttachSession(arg1, arg2) {
  return window['go']['main']['App']['AttachSession'](arg1, arg2);
}

export function BrowseDirectory(arg1) {
  return window['go']['main']['App']['BrowseDirectory'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearLog(arg1) {
  return window['go']['main']['App']['ClearLog'](arg1);
}

export function CloseTab(arg1, arg2) {
  return window['go']['main']['App']['CloseTab'](arg1, arg2);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSessionFromTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSessionFromTemplate'](arg1, arg2, arg3);
}

export function CreateTab(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateTab'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4, arg5);
}

export function CycleYoloMode(arg1, arg2) {
  return window['go']['main']['App']['CycleYoloMode'](arg1, arg2);
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function DeleteCommandGroup(arg1) {
  return window['go']['main']['App']['DeleteCommandGroup'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSessionTemplate(arg1) {
  return window['go']['main']['App']['DeleteSessionTemplate'](arg1);
}

export function DeleteSubtask(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSubtask'](arg1, arg2, arg3);
}

export function DeleteTab(arg1, arg2) {
  return window['go']['main']['App']['DeleteTab'](arg1, arg2);
}

export function DeleteTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteTask'](arg1, arg2);
}

export function DetachSession(arg1) {
  return window['go']['main']['App']['DetachSession'](arg1);
}

export function DetectionPatternsVersion() {
  return window['go']['main']['App']['DetectionPatternsVersion']();
}

export function DiscoverLocalSchemes() {
  return window['go']['main']['App']['DiscoverLocalSchemes']();
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function ExportSessions(arg1) {
  return window['go']['main']['App']['ExportSessions'](arg1);
}

export function FetchOnlineSchemes(arg1) {
  return window['go']['main']['App']['FetchOnlineSchemes'](arg1);
}

export function ForkSession(arg1, arg2) {
  return window['go']['main']['App']['ForkSession'](arg1, arg2);
}

export function ForkToNewSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForkToNewSession'](arg1, arg2, arg3);
}

export function ForkToNewTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForkToNewTab'](arg1, arg2, arg3);
}

export function GetActiveProjectID() {
  return window['go']['main']['App']['GetActiveProjectID']();
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetAllTasks() {
  return window['go']['main']['App']['GetAllTasks']();
}

export function GetAppLog() {
  return window['go']['main']['App']['GetAppLog']();
}

export function GetBackgroundAgentLogs(arg1) {
  return window['go']['main']['App']['GetBackgroundAgentLogs'](arg1);
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function GetClaudeUsage() {
  return window['go']['main']['App']['GetClaudeUsage']();
}

export function GetCodexUsage() {
  return window['go']['main']['App']['GetCodexUsage']();
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetExtraArgs(arg1, arg2) {
  return window['go']['main']['App']['GetExtraArgs'](arg1, arg2);
}

export function GetFullDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFullDiff'](arg1, arg2, arg3);
}

export function GetFullDiffFileList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFullDiffFileList'](arg1, arg2, arg3);
}

export function GetFullDiffFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFullDiffFiles'](arg1, arg2, arg3);
}

export function GetFullDiffForFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetFullDiffForFile'](arg1, arg2, arg3, arg4, arg5);
}

export function GetGitBranch(arg1) {
  return window['go']['main']['App']['GetGitBranch'](arg1);
}

export function GetGitCommitDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetGitCommitDiff'](arg1, arg2, arg3, arg4);
}

export function GetGitCommitFiles(arg1, arg2) {
  return window['go']['main']['App']['GetGitCommitFiles'](arg1, arg2);
}

export function GetGitHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGitHistory'](arg1, arg2, arg3);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetHistoryPreview(arg1) {
  return window['go']['main']['App']['GetHistoryPreview'](arg1);
}

export function GetLastLine(arg1) {
  return window['go']['main']['App']['GetLastLine'](arg1);
}

export function GetLockStatus() {
  return window['go']['main']['App']['GetLockStatus']();
}

export function GetLog(arg1) {
  return window['go']['main']['App']['GetLog'](arg1);
}

export function GetMultiplexerStatus() {
  return window['go']['main']['App']['GetMultiplexerStatus']();
}

export function GetNextTask(arg1) {
  return window['go']['main']['App']['GetNextTask'](arg1);
}

export function GetPreview(arg1, arg2) {
  return window['go']['main']['App']['GetPreview'](arg1, arg2);
}

export function GetProjectActivityStatistics(arg1, arg2) {
  return window['go']['main']['App']['GetProjectActivityStatistics'](arg1, arg2);
}

export function GetProjectGitSummaries(arg1) {
  return window['go']['main']['App']['GetProjectGitSummaries'](arg1);
}

export function GetProjectSessions(arg1) {
  return window['go']['main']['App']['GetProjectSessions'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetQuickJump() {
  return window['go']['main']['App']['GetQuickJump']();
}

export function GetResumeSessions(arg1, arg2) {
  return window['go']['main']['App']['GetResumeSessions'](arg1, arg2);
}

export function GetSessionDiff(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSessionDiff'](arg1, arg2, arg3);
}

export function GetSessionDiffFileList(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSessionDiffFileList'](arg1, arg2, arg3);
}

export function GetSessionDiffFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSessionDiffFiles'](arg1, arg2, arg3);
}

export function GetSessionDiffForFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetSessionDiffForFile'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSessionTemplates() {
  return window['go']['main']['App']['GetSessionTemplates']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSidebarUpdates() {
  return window['go']['main']['App']['GetSidebarUpdates']();
}

export function GetStatusLines() {
  return window['go']['main']['App']['GetStatusLines']();
}

export function GetTabNotes(arg1, arg2) {
  return window['go']['main']['App']['GetTabNotes'](arg1, arg2);
}

export function GetTabOrder(arg1) {
  return window['go']['main']['App']['GetTabOrder'](arg1);
}

export function GetTabWorkingDirectory(arg1, arg2) {
  return window['go']['main']['App']['GetTabWorkingDirectory'](arg1, arg2);
}

export function GetTaskBackups() {
  return window['go']['main']['App']['GetTaskBackups']();
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function GetTasksByStatus(arg1, arg2) {
  return window['go']['main']['App']['GetTasksByStatus'](arg1, arg2);
}

export function GetTerminalWSPort() {
  return window['go']['main']['App']['GetTerminalWSPort']();
}

export function GetTerminalWSToken() {
  return window['go']['main']['App']['GetTerminalWSToken']();
}

export function GetTrashItems() {
  return window['go']['main']['App']['GetTrashItems']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowAutoYes(arg1, arg2) {
  return window['go']['main']['App']['GetWindowAutoYes'](arg1, arg2);
}

export function GetWindowList(arg1) {
  return window['go']['main']['App']['GetWindowList'](arg1);
}

export function GlobalSearch(arg1) {
  return window['go']['main']['App']['GlobalSearch'](arg1);
}

export function ImportSchemeFiles() {
  return window['go']['main']['App']['ImportSchemeFiles']();
}

export function ImportSessionFile(arg1, arg2) {
  return window['go']['main']['App']['ImportSessionFile'](arg1, arg2);
}

export function ImportSessions(arg1, arg2) {
  return window['go']['main']['App']['ImportSessions'](arg1, arg2);
}

export function InitHistorySearch() {
  return window['go']['main']['App']['InitHistorySearch']();
}

export function InstallMultiplexer() {
  return window['go']['main']['App']['InstallMultiplexer']();
}

export function InvalidateSessionFileIndex(arg1) {
  return window['go']['main']['App']['InvalidateSessionFileIndex'](arg1);
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function ListBackgroundAgents() {
  return window['go']['main']['App']['ListBackgroundAgents']();
}

export function ListGitBranches(arg1) {
  return window['go']['main']['App']['ListGitBranches'](arg1);
}

export function ListOnlineSchemes() {
  return window['go']['main']['App']['ListOnlineSchemes']();
}

export function ListSessionDirectory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListSessionDirectory'](arg1, arg2, arg3, arg4);
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function MoveGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveGroup'](arg1, arg2);
}

export function MoveQuickJump(arg1, arg2) {
  return window['go']['main']['App']['MoveQuickJump'](arg1, arg2);
}

export function MoveSessionToIndex(arg1, arg2) {
  return window['go']['main']['App']['MoveSessionToIndex'](arg1, arg2);
}

export function MoveTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2, arg3);
}

export function OpenAppLogFolder() {
  return window['go']['main']['App']['OpenAppLogFolder']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function OpenLogFolder(arg1) {
  return window['go']['main']['App']['OpenLogFolder'](arg1);
}

export function OpenSessionFileForEdit(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenSessionFileForEdit'](arg1, arg2, arg3, arg4);
}

export function PendingUpdate() {
  return window['go']['main']['App']['PendingUpdate']();
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function PermanentlyDeleteTrashItem(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteTrashItem'](arg1);
}

export function QuickReplyTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['QuickReplyTab'](arg1, arg2, arg3);
}

export function ReadSessionDirectoryFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReadSessionDirectoryFile'](arg1, arg2, arg3, arg4);
}

export function ReadSessionFile() {
  return window['go']['main']['App']['ReadSessionFile']();
}

export function RedrawWindow(arg1, arg2) {
  return window['go']['main']['App']['RedrawWindow'](arg1, arg2);
}

export function RefreshDetectionPatterns() {
  return window['go']['main']['App']['RefreshDetectionPatterns']();
}

export function RefreshWindow(arg1, arg2) {
  return window['go']['main']['App']['RefreshWindow'](arg1, arg2);
}

export function RemoveQuickJump(arg1, arg2) {
  return window['go']['main']['App']['RemoveQuickJump'](arg1, arg2);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RenameTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2, arg3);
}

export function ReorderSession(arg1, arg2) {
  return window['go']['main']['App']['ReorderSession'](arg1, arg2);
}

export function ReorderTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderTab'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartTab(arg1, arg2) {
  return window['go']['main']['App']['RestartTab'](arg1, arg2);
}

export function RestartTabWithResume(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartTabWithResume'](arg1, arg2, arg3);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RestoreDeletedSubtask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestoreDeletedSubtask'](arg1, arg2, arg3, arg4);
}

export function RestoreDeletedTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreDeletedTask'](arg1, arg2, arg3);
}

export function RestoreTaskBackup(arg1) {
  return window['go']['main']['App']['RestoreTaskBackup'](arg1);
}

export function RestoreTrashItem(arg1) {
  return window['go']['main']['App']['RestoreTrashItem'](arg1);
}

export function RevertDiffFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RevertDiffFile'](arg1, arg2, arg3, arg4, arg5);
}

export function RevertDiffHunk(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RevertDiffHunk'](arg1, arg2, arg3, arg4);
}

export function RunCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2, arg3, arg4);
}

export function SaveCommand(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveCommand'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveCommandGroup(arg1, arg2) {
  return window['go']['main']['App']['SaveCommandGroup'](arg1, arg2);
}

export function SaveSessionAsTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveSessionAsTemplate'](arg1, arg2, arg3);
}

export function SaveSessionFileEdit(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveSessionFileEdit'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveSessionTemplate(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SaveSessionTemplate'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchSessionFileContents(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SearchSessionFileContents'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SearchSessionFileIndex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchSessionFileIndex'](arg1, arg2, arg3, arg4);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SendPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendPrompt'](arg1, arg2);
}

export function SendPromptToWindow(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendPromptToWindow'](arg1, arg2, arg3);
}

export function SendTaskToAgent(arg1, arg2) {
  return window['go']['main']['App']['SendTaskToAgent'](arg1, arg2);
}

export function SetExtraArgs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetExtraArgs'](arg1, arg2, arg3);
}

export function SetGroupColor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetGroupColor'](arg1, arg2, arg3, arg4);
}

export function SetLastWindowIndex(arg1, arg2) {
  return window['go']['main']['App']['SetLastWindowIndex'](arg1, arg2);
}

export function SetQuickJump(arg1) {
  return window['go']['main']['App']['SetQuickJump'](arg1);
}

export function SetQuickJumpLabel(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetQuickJumpLabel'](arg1, arg2, arg3);
}

export function SetSessionColor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSessionColor'](arg1, arg2, arg3, arg4);
}

export function SetSessionNotes(arg1, arg2) {
  return window['go']['main']['App']['SetSessionNotes'](arg1, arg2);
}

export function SetTabColor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetTabColor'](arg1, arg2, arg3, arg4);
}

export function SetTabFontSize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTabFontSize'](arg1, arg2, arg3);
}

export function SetTabNotes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTabNotes'](arg1, arg2, arg3);
}

export function SetTabStatusBar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTabStatusBar'](arg1, arg2, arg3);
}

export function SetTabStatusLineVisibility(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTabStatusLineVisibility'](arg1, arg2, arg3);
}

export function SetTabTerminalTheme(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTabTerminalTheme'](arg1, arg2, arg3);
}

export function SetTabViewBar(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTabViewBar'](arg1, arg2, arg3);
}

export function SetWindowAutoYes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWindowAutoYes'](arg1, arg2, arg3);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StartSessionWithResume(arg1, arg2) {
  return window['go']['main']['App']['StartSessionWithResume'](arg1, arg2);
}

export function StopBackgroundAgent(arg1) {
  return window['go']['main']['App']['StopBackgroundAgent'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function StopTab(arg1, arg2) {
  return window['go']['main']['App']['StopTab'](arg1, arg2);
}

export function StopTaskMaster(arg1) {
  return window['go']['main']['App']['StopTaskMaster'](arg1);
}

export function TaskMasterAddDependency(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterAddDependency'](arg1, arg2, arg3);
}

export function TaskMasterAddManualTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TaskMasterAddManualTask'](arg1, arg2, arg3, arg4, arg5);
}

export function TaskMasterAddSubtask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TaskMasterAddSubtask'](arg1, arg2, arg3, arg4);
}

export function TaskMasterAddTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TaskMasterAddTask'](arg1, arg2, arg3, arg4);
}

export function TaskMasterAnalyzeComplexity(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterAnalyzeComplexity'](arg1, arg2);
}

export function TaskMasterClearSubtasks(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterClearSubtasks'](arg1, arg2);
}

export function TaskMasterExpandAll(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterExpandAll'](arg1, arg2);
}

export function TaskMasterExpandTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TaskMasterExpandTask'](arg1, arg2, arg3, arg4);
}

export function TaskMasterGetTask(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterGetTask'](arg1, arg2);
}

export function TaskMasterGetTasks(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterGetTasks'](arg1, arg2);
}

export function TaskMasterInit(arg1) {
  return window['go']['main']['App']['TaskMasterInit'](arg1);
}

export function TaskMasterNextTask(arg1) {
  return window['go']['main']['App']['TaskMasterNextTask'](arg1);
}

export function TaskMasterParsePRD(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterParsePRD'](arg1, arg2, arg3);
}

export function TaskMasterRemoveDependency(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterRemoveDependency'](arg1, arg2, arg3);
}

export function TaskMasterRemoveSubtask(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterRemoveSubtask'](arg1, arg2);
}

export function TaskMasterRemoveTask(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterRemoveTask'](arg1, arg2);
}

export function TaskMasterSendToAgent(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterSendToAgent'](arg1, arg2);
}

export function TaskMasterSetStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterSetStatus'](arg1, arg2, arg3);
}

export function TaskMasterSetSubtaskStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterSetSubtaskStatus'](arg1, arg2, arg3);
}

export function TaskMasterStatus(arg1) {
  return window['go']['main']['App']['TaskMasterStatus'](arg1);
}

export function TaskMasterUpdateSubtask(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterUpdateSubtask'](arg1, arg2, arg3);
}

export function TaskMasterUpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TaskMasterUpdateTask'](arg1, arg2, arg3, arg4);
}

export function TaskMasterUpdateTaskDirect(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['TaskMasterUpdateTaskDirect'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function ToggleAutoYes(arg1) {
  return window['go']['main']['App']['ToggleAutoYes'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function ToggleGroupCollapse(arg1) {
  return window['go']['main']['App']['ToggleGroupCollapse'](arg1);
}

export function ToggleSubtask(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleSubtask'](arg1, arg2, arg3);
}

export function UnfinishedTasksForSession(arg1) {
  return window['go']['main']['App']['UnfinishedTasksForSession'](arg1);
}

export function UpdateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3);
}
