// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubtask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSubtask'](arg1, arg2, arg3);
}

export function AssignToGroup(arg1, arg2) {
  return window['go']['main']['App']['AssignToGroup'](arg1, arg2);
}

export function AttachBackgroundAgent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AttachBackgroundAgent'](arg1, arg2, arg3, arg4);
}

export function AttachBackgroundAgentAsTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttachBackgroundAgentAsTab'](arg1, arg2, arg3);
}

export function AttachSession(arg1, arg2) {
  return window['go']['main']['App']['AttachSession'](arg1, arg2);
}

export function BrowseDirectory(arg1) {
  return window['go']['main']['App']['BrowseDirectory'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CloseTab(arg1, arg2) {
  return window['go']['main']['App']['CloseTab'](arg1, arg2);
}

export function CreateBackup() {
  return window['go']['main']['App']['CreateBackup']();
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateTab(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CreateTab'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CreateTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3, arg4, arg5);
}

export function CycleYoloMode(arg1, arg2) {
  return window['go']['main']['App']['CycleYoloMode'](arg1, arg2);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteSubtask(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteSubtask'](arg1, arg2, arg3);
}

export function DeleteTab(arg1, arg2) {
  return window['go']['main']['App']['DeleteTab'](arg1, arg2);
}

export function DeleteTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteTask'](arg1, arg2);
}

export function DetachSession(arg1) {
  return window['go']['main']['App']['DetachSession'](arg1);
}

export function EmptyTrash() {
  return window['go']['main']['App']['EmptyTrash']();
}

export function ForkSession(arg1) {
  return window['go']['main']['App']['ForkSession'](arg1);
}

export function ForkToNewSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForkToNewSession'](arg1, arg2, arg3);
}

export function ForkToNewTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ForkToNewTab'](arg1, arg2, arg3);
}

export function GetActiveProjectID() {
  return window['go']['main']['App']['GetActiveProjectID']();
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetBackgroundAgentLogs(arg1) {
  return window['go']['main']['App']['GetBackgroundAgentLogs'](arg1);
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function GetClaudeUsage() {
  return window['go']['main']['App']['GetClaudeUsage']();
}

export function GetCodexUsage() {
  return window['go']['main']['App']['GetCodexUsage']();
}

export function GetExtraArgs(arg1, arg2) {
  return window['go']['main']['App']['GetExtraArgs'](arg1, arg2);
}

export function GetFullDiff(arg1) {
  return window['go']['main']['App']['GetFullDiff'](arg1);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetHistoryPreview(arg1) {
  return window['go']['main']['App']['GetHistoryPreview'](arg1);
}

export function GetLastLine(arg1) {
  return window['go']['main']['App']['GetLastLine'](arg1);
}

export function GetLockStatus() {
  return window['go']['main']['App']['GetLockStatus']();
}

export function GetNextTask(arg1) {
  return window['go']['main']['App']['GetNextTask'](arg1);
}

export function GetPreview(arg1, arg2) {
  return window['go']['main']['App']['GetPreview'](arg1, arg2);
}

export function GetProjectActivityStatistics(arg1, arg2) {
  return window['go']['main']['App']['GetProjectActivityStatistics'](arg1, arg2);
}

export function GetProjectGitSummaries(arg1) {
  return window['go']['main']['App']['GetProjectGitSummaries'](arg1);
}

export function GetProjectSessions(arg1) {
  return window['go']['main']['App']['GetProjectSessions'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetResumeSessions(arg1, arg2) {
  return window['go']['main']['App']['GetResumeSessions'](arg1, arg2);
}

export function GetSessionDiff(arg1) {
  return window['go']['main']['App']['GetSessionDiff'](arg1);
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSidebarUpdates() {
  return window['go']['main']['App']['GetSidebarUpdates']();
}

export function GetStatusLines() {
  return window['go']['main']['App']['GetStatusLines']();
}

export function GetTabNotes(arg1, arg2) {
  return window['go']['main']['App']['GetTabNotes'](arg1, arg2);
}

export function GetTabOrder(arg1) {
  return window['go']['main']['App']['GetTabOrder'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['main']['App']['GetTasks'](arg1);
}

export function GetTasksByStatus(arg1, arg2) {
  return window['go']['main']['App']['GetTasksByStatus'](arg1, arg2);
}

export function GetTerminalWSPort() {
  return window['go']['main']['App']['GetTerminalWSPort']();
}

export function GetTerminalWSToken() {
  return window['go']['main']['App']['GetTerminalWSToken']();
}

export function GetTrashItems() {
  return window['go']['main']['App']['GetTrashItems']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowAutoYes(arg1, arg2) {
  return window['go']['main']['App']['GetWindowAutoYes'](arg1, arg2);
}

export function GetWindowList(arg1) {
  return window['go']['main']['App']['GetWindowList'](arg1);
}

export function GlobalSearch(arg1) {
  return window['go']['main']['App']['GlobalSearch'](arg1);
}

export function ImportSessions(arg1, arg2) {
  return window['go']['main']['App']['ImportSessions'](arg1, arg2);
}

export function InitHistorySearch() {
  return window['go']['main']['App']['InitHistorySearch']();
}

export function IsDevMode() {
  return window['go']['main']['App']['IsDevMode']();
}

export function ListBackgroundAgents() {
  return window['go']['main']['App']['ListBackgroundAgents']();
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function MoveSessionToIndex(arg1, arg2) {
  return window['go']['main']['App']['MoveSessionToIndex'](arg1, arg2);
}

export function MoveTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveTask'](arg1, arg2, arg3);
}

export function PerformUpdate(arg1) {
  return window['go']['main']['App']['PerformUpdate'](arg1);
}

export function PermanentlyDeleteTrashItem(arg1) {
  return window['go']['main']['App']['PermanentlyDeleteTrashItem'](arg1);
}

export function QuickReplyTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['QuickReplyTab'](arg1, arg2, arg3);
}

export function RefreshWindow(arg1, arg2) {
  return window['go']['main']['App']['RefreshWindow'](arg1, arg2);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function RenameTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameTab'](arg1, arg2, arg3);
}

export function ReorderSession(arg1, arg2) {
  return window['go']['main']['App']['ReorderSession'](arg1, arg2);
}

export function ReorderTab(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderTab'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestartTab(arg1, arg2) {
  return window['go']['main']['App']['RestartTab'](arg1, arg2);
}

export function RestartTabWithResume(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestartTabWithResume'](arg1, arg2, arg3);
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function RestoreTrashItem(arg1) {
  return window['go']['main']['App']['RestoreTrashItem'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function SendInput(arg1, arg2) {
  return window['go']['main']['App']['SendInput'](arg1, arg2);
}

export function SendPrompt(arg1, arg2) {
  return window['go']['main']['App']['SendPrompt'](arg1, arg2);
}

export function SendTaskToAgent(arg1, arg2) {
  return window['go']['main']['App']['SendTaskToAgent'](arg1, arg2);
}

export function SetExtraArgs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetExtraArgs'](arg1, arg2, arg3);
}

export function SetGroupColor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetGroupColor'](arg1, arg2, arg3, arg4);
}

export function SetSessionColor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetSessionColor'](arg1, arg2, arg3, arg4);
}

export function SetSessionNotes(arg1, arg2) {
  return window['go']['main']['App']['SetSessionNotes'](arg1, arg2);
}

export function SetTabColor(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetTabColor'](arg1, arg2, arg3, arg4);
}

export function SetTabNotes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTabNotes'](arg1, arg2, arg3);
}

export function SetTabStatusLineVisibility(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTabStatusLineVisibility'](arg1, arg2, arg3);
}

export function SetWindowAutoYes(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWindowAutoYes'](arg1, arg2, arg3);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function StartSessionWithResume(arg1, arg2) {
  return window['go']['main']['App']['StartSessionWithResume'](arg1, arg2);
}

export function StopBackgroundAgent(arg1) {
  return window['go']['main']['App']['StopBackgroundAgent'](arg1);
}

export function StopSession(arg1) {
  return window['go']['main']['App']['StopSession'](arg1);
}

export function StopTab(arg1, arg2) {
  return window['go']['main']['App']['StopTab'](arg1, arg2);
}

export function StopTaskMaster(arg1) {
  return window['go']['main']['App']['StopTaskMaster'](arg1);
}

export function TaskMasterAddDependency(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterAddDependency'](arg1, arg2, arg3);
}

export function TaskMasterAddManualTask(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TaskMasterAddManualTask'](arg1, arg2, arg3, arg4, arg5);
}

export function TaskMasterAddSubtask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TaskMasterAddSubtask'](arg1, arg2, arg3, arg4);
}

export function TaskMasterAddTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TaskMasterAddTask'](arg1, arg2, arg3, arg4);
}

export function TaskMasterAnalyzeComplexity(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterAnalyzeComplexity'](arg1, arg2);
}

export function TaskMasterClearSubtasks(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterClearSubtasks'](arg1, arg2);
}

export function TaskMasterExpandAll(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterExpandAll'](arg1, arg2);
}

export function TaskMasterExpandTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TaskMasterExpandTask'](arg1, arg2, arg3, arg4);
}

export function TaskMasterGetTask(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterGetTask'](arg1, arg2);
}

export function TaskMasterGetTasks(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterGetTasks'](arg1, arg2);
}

export function TaskMasterInit(arg1) {
  return window['go']['main']['App']['TaskMasterInit'](arg1);
}

export function TaskMasterNextTask(arg1) {
  return window['go']['main']['App']['TaskMasterNextTask'](arg1);
}

export function TaskMasterParsePRD(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterParsePRD'](arg1, arg2, arg3);
}

export function TaskMasterRemoveDependency(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterRemoveDependency'](arg1, arg2, arg3);
}

export function TaskMasterRemoveSubtask(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterRemoveSubtask'](arg1, arg2);
}

export function TaskMasterRemoveTask(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterRemoveTask'](arg1, arg2);
}

export function TaskMasterSendToAgent(arg1, arg2) {
  return window['go']['main']['App']['TaskMasterSendToAgent'](arg1, arg2);
}

export function TaskMasterSetStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterSetStatus'](arg1, arg2, arg3);
}

export function TaskMasterSetSubtaskStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterSetSubtaskStatus'](arg1, arg2, arg3);
}

export function TaskMasterStatus(arg1) {
  return window['go']['main']['App']['TaskMasterStatus'](arg1);
}

export function TaskMasterUpdateSubtask(arg1, arg2, arg3) {
  return window['go']['main']['App']['TaskMasterUpdateSubtask'](arg1, arg2, arg3);
}

export function TaskMasterUpdateTask(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TaskMasterUpdateTask'](arg1, arg2, arg3, arg4);
}

export function TaskMasterUpdateTaskDirect(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TaskMasterUpdateTaskDirect'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ToggleAutoYes(arg1) {
  return window['go']['main']['App']['ToggleAutoYes'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function ToggleGroupCollapse(arg1) {
  return window['go']['main']['App']['ToggleGroupCollapse'](arg1);
}

export function ToggleSubtask(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleSubtask'](arg1, arg2, arg3);
}

export function UpdateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2, arg3);
}
