// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {session} from '../models';

export function AddSubtask(arg1:string,arg2:string,arg3:string):Promise<main.SubtaskInfo>;

export function AssignToGroup(arg1:string,arg2:string):Promise<void>;

export function AttachSession(arg1:string,arg2:number):Promise<string>;

export function BrowseDirectory(arg1:string):Promise<string>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function CloseTab(arg1:string,arg2:number):Promise<void>;

export function CreateGroup(arg1:string):Promise<main.GroupInfo>;

export function CreateProject(arg1:string):Promise<main.ProjectInfo>;

export function CreateSession(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string):Promise<main.SessionInfo>;

export function CreateTab(arg1:string,arg2:boolean,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CreateTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<main.TaskInfo>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSubtask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteTab(arg1:string,arg2:number):Promise<void>;

export function DeleteTask(arg1:string,arg2:string):Promise<void>;

export function DetachSession(arg1:string):Promise<void>;

export function ForkSession(arg1:string):Promise<main.ForkResult>;

export function ForkToNewSession(arg1:string,arg2:string,arg3:string):Promise<main.SessionInfo>;

export function ForkToNewTab(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetActiveProjectID():Promise<string>;

export function GetActivities():Promise<Record<string, string>>;

export function GetAgents():Promise<Array<main.AgentInfo>>;

export function GetExtraArgs(arg1:string,arg2:number):Promise<string>;

export function GetFullDiff(arg1:string):Promise<main.DiffData>;

export function GetGroups():Promise<Array<main.GroupInfo>>;

export function GetHistoryPreview(arg1:main.HistoryEntryInfo):Promise<string>;

export function GetLastLine(arg1:string):Promise<string>;

export function GetNextTask(arg1:string):Promise<main.TaskInfo>;

export function GetPreview(arg1:string,arg2:number):Promise<main.PreviewData>;

export function GetProjectSessions(arg1:string):Promise<Array<main.SessionInfo>>;

export function GetProjects():Promise<Array<main.ProjectInfo>>;

export function GetResumeSessions(arg1:string,arg2:string):Promise<Array<main.AgentSessionInfo>>;

export function GetSessionDiff(arg1:string):Promise<main.DiffData>;

export function GetSessions():Promise<Array<main.SessionInfo>>;

export function GetSettings():Promise<main.SettingsInfo>;

export function GetSidebarUpdates():Promise<main.SidebarUpdate>;

export function GetStatusLines():Promise<Record<string, string>>;

export function GetTabNotes(arg1:string,arg2:number):Promise<string>;

export function GetTabOrder(arg1:string):Promise<Array<number>>;

export function GetTasks(arg1:string):Promise<Array<main.TaskInfo>>;

export function GetTasksByStatus(arg1:string,arg2:string):Promise<Array<main.TaskInfo>>;

export function GetTerminalWSPort():Promise<number>;

export function GetWindowAutoYes(arg1:string,arg2:number):Promise<boolean>;

export function GetWindowList(arg1:string):Promise<Array<session.WindowInfo>>;

export function GlobalSearch(arg1:string):Promise<Array<main.HistoryEntryInfo>>;

export function ImportSessions(arg1:string,arg2:Array<string>):Promise<number>;

export function InitHistorySearch():Promise<void>;

export function IsDevMode():Promise<boolean>;

export function MoveSessionToIndex(arg1:string,arg2:number):Promise<void>;

export function MoveTask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PerformUpdate(arg1:string):Promise<void>;

export function RefreshWindow(arg1:string,arg2:number):Promise<void>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function RenameTab(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ReorderSession(arg1:string,arg2:number):Promise<void>;

export function ReorderTab(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartTab(arg1:string,arg2:number):Promise<void>;

export function RestartTabWithResume(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SaveSettings(arg1:main.SettingsInfo):Promise<void>;

export function SelectProject(arg1:string):Promise<void>;

export function SendInput(arg1:string,arg2:string):Promise<void>;

export function SendPrompt(arg1:string,arg2:string):Promise<void>;

export function SendTaskToAgent(arg1:string,arg2:string):Promise<void>;

export function SetExtraArgs(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetGroupColor(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetSessionColor(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function SetSessionNotes(arg1:string,arg2:string):Promise<void>;

export function SetTabNotes(arg1:string,arg2:number,arg3:string):Promise<void>;

export function SetWindowAutoYes(arg1:string,arg2:number,arg3:boolean):Promise<void>;

export function StartSession(arg1:string):Promise<void>;

export function StartSessionWithResume(arg1:string,arg2:string):Promise<void>;

export function StopSession(arg1:string):Promise<void>;

export function StopTab(arg1:string,arg2:number):Promise<void>;

export function StopTaskMaster(arg1:string):Promise<void>;

export function TaskMasterAddDependency(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterAddManualTask(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<main.MCPTaskInfo>;

export function TaskMasterAddSubtask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TaskMasterAddTask(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<main.MCPTaskInfo>;

export function TaskMasterAnalyzeComplexity(arg1:string,arg2:boolean):Promise<string>;

export function TaskMasterClearSubtasks(arg1:string,arg2:string):Promise<void>;

export function TaskMasterExpandAll(arg1:string,arg2:boolean):Promise<void>;

export function TaskMasterExpandTask(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<void>;

export function TaskMasterGetTask(arg1:string,arg2:string):Promise<main.MCPTaskInfo>;

export function TaskMasterGetTasks(arg1:string,arg2:string):Promise<Array<main.MCPTaskInfo>>;

export function TaskMasterInit(arg1:string):Promise<void>;

export function TaskMasterNextTask(arg1:string):Promise<main.MCPTaskInfo>;

export function TaskMasterParsePRD(arg1:string,arg2:string,arg3:number):Promise<void>;

export function TaskMasterRemoveDependency(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterRemoveSubtask(arg1:string,arg2:string):Promise<void>;

export function TaskMasterRemoveTask(arg1:string,arg2:string):Promise<void>;

export function TaskMasterSendToAgent(arg1:string,arg2:string):Promise<void>;

export function TaskMasterSetStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterSetSubtaskStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterStatus(arg1:string):Promise<Record<string, any>>;

export function TaskMasterUpdateSubtask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TaskMasterUpdateTask(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function TaskMasterUpdateTaskDirect(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function ToggleAutoYes(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:string):Promise<void>;

export function ToggleGroupCollapse(arg1:string):Promise<void>;

export function ToggleSubtask(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateTask(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;
