// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AudioTest() {
  return window['go']['main']['DictationService']['AudioTest']();
}

export function ClearBuffer() {
  return window['go']['main']['DictationService']['ClearBuffer']();
}

export function GetAvailableLanguages() {
  return window['go']['main']['DictationService']['GetAvailableLanguages']();
}

export function GetBufferText() {
  return window['go']['main']['DictationService']['GetBufferText']();
}

export function GetDictationSettings() {
  return window['go']['main']['DictationService']['GetDictationSettings']();
}

export function GetInputDevices() {
  return window['go']['main']['DictationService']['GetInputDevices']();
}

export function GetVoiceLevel() {
  return window['go']['main']['DictationService']['GetVoiceLevel']();
}

export function Initialize() {
  return window['go']['main']['DictationService']['Initialize']();
}

export function IsListening() {
  return window['go']['main']['DictationService']['IsListening']();
}

export function SendBufferText() {
  return window['go']['main']['DictationService']['SendBufferText']();
}

export function SetActiveTmuxSession(arg1, arg2) {
  return window['go']['main']['DictationService']['SetActiveTmuxSession'](arg1, arg2);
}

export function SetBufferText(arg1) {
  return window['go']['main']['DictationService']['SetBufferText'](arg1);
}

export function SetBufferTextCallback(arg1) {
  return window['go']['main']['DictationService']['SetBufferTextCallback'](arg1);
}

export function SetDictationSettings(arg1) {
  return window['go']['main']['DictationService']['SetDictationSettings'](arg1);
}

export function SetDictationTarget(arg1) {
  return window['go']['main']['DictationService']['SetDictationTarget'](arg1);
}

export function SetErrorCallback(arg1) {
  return window['go']['main']['DictationService']['SetErrorCallback'](arg1);
}

export function SetFieldDeleteCallback(arg1) {
  return window['go']['main']['DictationService']['SetFieldDeleteCallback'](arg1);
}

export function SetFieldTextCallback(arg1) {
  return window['go']['main']['DictationService']['SetFieldTextCallback'](arg1);
}

export function SetInputDevice(arg1) {
  return window['go']['main']['DictationService']['SetInputDevice'](arg1);
}

export function SetInterimTextCallback(arg1) {
  return window['go']['main']['DictationService']['SetInterimTextCallback'](arg1);
}

export function SetStateChangeCallback(arg1) {
  return window['go']['main']['DictationService']['SetStateChangeCallback'](arg1);
}

export function SetTerminalServer(arg1) {
  return window['go']['main']['DictationService']['SetTerminalServer'](arg1);
}

export function SetVoiceLevelCallback(arg1) {
  return window['go']['main']['DictationService']['SetVoiceLevelCallback'](arg1);
}

export function Shutdown() {
  return window['go']['main']['DictationService']['Shutdown']();
}

export function ToggleDictation() {
  return window['go']['main']['DictationService']['ToggleDictation']();
}
