// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AudioTest():Promise<void>;

export function ClearBuffer():Promise<void>;

export function GetAvailableLanguages():Promise<Array<Record<string, string>>>;

export function GetBufferText():Promise<string>;

export function GetDictationSettings():Promise<main.DictationSettings>;

export function GetInputDevices():Promise<Array<main.InputDevice>>;

export function GetVoiceLevel():Promise<number>;

export function Initialize():Promise<void>;

export function IsListening():Promise<boolean>;

export function SendBufferText():Promise<void>;

export function SetActiveTmuxSession(arg1:string,arg2:number):Promise<void>;

export function SetBufferText(arg1:string):Promise<void>;

export function SetBufferTextCallback(arg1:any):Promise<void>;

export function SetDictationSettings(arg1:string):Promise<void>;

export function SetDictationTarget(arg1:string):Promise<void>;

export function SetErrorCallback(arg1:any):Promise<void>;

export function SetFieldDeleteCallback(arg1:any):Promise<void>;

export function SetFieldTextCallback(arg1:any):Promise<void>;

export function SetInputDevice(arg1:string):Promise<void>;

export function SetInterimTextCallback(arg1:any):Promise<void>;

export function SetStateChangeCallback(arg1:any):Promise<void>;

export function SetTerminalServer(arg1:main.TerminalServer):Promise<void>;

export function SetVoiceLevelCallback(arg1:any):Promise<void>;

export function Shutdown():Promise<void>;

export function ToggleDictation():Promise<boolean>;
